"""QuantX — Seed built-in indicators into the database."""

import json

BUILTIN_INDICATORS = [
    {"indicator_id": "EMA", "name": "Exponential Moving Average", "display_name": "EMA",
     "category": "trend", "description": "Weighted average giving more importance to recent prices",
     "output_type": "single", "output_labels": ["ema"],
     "params": [{"name": "period", "label": "Period", "type": "int", "default": 20, "min": 2, "max": 500}],
     "usage_example": "calc_ema(close, 20)"},
    {"indicator_id": "SMA", "name": "Simple Moving Average", "display_name": "SMA",
     "category": "trend", "description": "Average price over a fixed lookback window",
     "output_type": "single", "output_labels": ["sma"],
     "params": [{"name": "period", "label": "Period", "type": "int", "default": 20, "min": 2, "max": 500}],
     "usage_example": "calc_sma(close, 20)"},
    {"indicator_id": "WMA", "name": "Weighted Moving Average", "display_name": "WMA",
     "category": "trend", "description": "Moving average weighted linearly by recency",
     "output_type": "single", "output_labels": ["wma"],
     "params": [{"name": "period", "label": "Period", "type": "int", "default": 20, "min": 2, "max": 500}],
     "usage_example": "calc_wma(close, 20)"},
    {"indicator_id": "HMA", "name": "Hull Moving Average", "display_name": "HMA",
     "category": "trend", "description": "Fast and smooth moving average by Alan Hull",
     "output_type": "single", "output_labels": ["hma"],
     "params": [{"name": "period", "label": "Period", "type": "int", "default": 20, "min": 2, "max": 500}],
     "usage_example": "calc_hma(close, 20)"},
    {"indicator_id": "RSI", "name": "Relative Strength Index", "display_name": "RSI",
     "category": "momentum", "description": "Oscillator measuring speed of price changes (0-100)",
     "output_type": "single", "output_labels": ["rsi"],
     "params": [{"name": "period", "label": "Period", "type": "int", "default": 14, "min": 2, "max": 100}],
     "usage_example": "calc_rsi(close, 14)"},
    {"indicator_id": "MACD", "name": "MACD", "display_name": "MACD",
     "category": "momentum", "description": "Moving average convergence divergence — trend following momentum",
     "output_type": "triple", "output_labels": ["macd_line", "signal_line", "histogram"],
     "params": [{"name": "fast", "label": "Fast", "type": "int", "default": 12, "min": 2, "max": 100},
                {"name": "slow", "label": "Slow", "type": "int", "default": 26, "min": 5, "max": 200},
                {"name": "signal", "label": "Signal", "type": "int", "default": 9, "min": 2, "max": 50}],
     "usage_example": "calc_macd(close, 12, 26, 9)"},
    {"indicator_id": "BB", "name": "Bollinger Bands", "display_name": "BB",
     "category": "volatility", "description": "SMA with upper/lower bands at N standard deviations",
     "output_type": "triple", "output_labels": ["upper", "middle", "lower"],
     "params": [{"name": "period", "label": "Period", "type": "int", "default": 20, "min": 5, "max": 200},
                {"name": "std_dev", "label": "Std Dev", "type": "float", "default": 2.0, "min": 0.5, "max": 5.0}],
     "usage_example": "calc_bbands(close, 20, 2.0)"},
    {"indicator_id": "ATR", "name": "Average True Range", "display_name": "ATR",
     "category": "volatility", "description": "Measures market volatility using high-low-close range",
     "output_type": "single", "output_labels": ["atr"],
     "params": [{"name": "period", "label": "Period", "type": "int", "default": 14, "min": 2, "max": 100}],
     "usage_example": "calc_atr(high, low, close, 14)"},
    {"indicator_id": "ROC", "name": "Rate of Change", "display_name": "ROC",
     "category": "momentum", "description": "Percentage change from N bars ago",
     "output_type": "single", "output_labels": ["roc"],
     "params": [{"name": "period", "label": "Period", "type": "int", "default": 10, "min": 1, "max": 200}],
     "usage_example": "calc_roc(close, 10)"},
    {"indicator_id": "ZSCORE", "name": "Z-Score", "display_name": "Z-Score",
     "category": "momentum", "description": "Standard deviations from rolling mean — measures extremeness",
     "output_type": "single", "output_labels": ["zscore"],
     "params": [{"name": "period", "label": "Period", "type": "int", "default": 20, "min": 5, "max": 200}],
     "usage_example": "calc_zscore(close, 20)"},
    {"indicator_id": "STOCH", "name": "Stochastic Oscillator", "display_name": "Stochastic",
     "category": "momentum", "description": "%K and %D oscillator comparing close to high-low range (0-100)",
     "output_type": "dual", "output_labels": ["k_line", "d_line"],
     "params": [{"name": "k_period", "label": "K Period", "type": "int", "default": 14, "min": 2, "max": 100},
                {"name": "d_period", "label": "D Period", "type": "int", "default": 3, "min": 1, "max": 50}],
     "usage_example": "calc_stoch(high, low, close, 14, 3)"},
    {"indicator_id": "WILLIAMS_R", "name": "Williams %R", "display_name": "Williams %R",
     "category": "momentum", "description": "Momentum oscillator (-100 to 0) — overbought/oversold",
     "output_type": "single", "output_labels": ["williams_r"],
     "params": [{"name": "period", "label": "Period", "type": "int", "default": 14, "min": 2, "max": 100}],
     "usage_example": "calc_williams_r(high, low, close, 14)"},
    {"indicator_id": "OBV", "name": "On-Balance Volume", "display_name": "OBV",
     "category": "volume", "description": "Cumulative volume momentum — rising OBV = accumulation",
     "output_type": "single", "output_labels": ["obv"],
     "params": [],
     "usage_example": "calc_obv(close, volume)"},
    {"indicator_id": "VWAP", "name": "Volume Weighted Average Price", "display_name": "VWAP",
     "category": "volume", "description": "Average price weighted by volume — institutional benchmark",
     "output_type": "single", "output_labels": ["vwap"],
     "params": [],
     "usage_example": "calc_vwap(high, low, close, volume)"},
    {"indicator_id": "DONCHIAN", "name": "Donchian Channel", "display_name": "Donchian",
     "category": "volatility", "description": "Highest high and lowest low over N periods — breakout channel",
     "output_type": "dual", "output_labels": ["upper", "lower"],
     "params": [{"name": "period", "label": "Period", "type": "int", "default": 20, "min": 2, "max": 200}],
     "usage_example": "calc_donchian(high, low, 20)"},
    {"indicator_id": "SUPERTREND", "name": "Supertrend", "display_name": "Supertrend",
     "category": "trend", "description": "Trend following indicator using ATR bands — direction: 1=bull, -1=bear",
     "output_type": "dual", "output_labels": ["supertrend", "direction"],
     "params": [{"name": "period", "label": "Period", "type": "int", "default": 10, "min": 2, "max": 100},
                {"name": "multiplier", "label": "Multiplier", "type": "float", "default": 3.0, "min": 0.5, "max": 10.0}],
     "usage_example": "calc_supertrend(high, low, close, 10, 3.0)"},
]


def seed_builtin_indicators(conn):
    """Insert all built-in indicators if not already present."""
    for ind in BUILTIN_INDICATORS:
        try:
            conn.execute(
                """INSERT OR IGNORE INTO indicators
                   (indicator_id, name, display_name, category, description,
                    output_type, output_labels, params, calc_code, usage_example,
                    is_builtin, is_approved, created_by)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 1, 'system')""",
                (ind["indicator_id"], ind["name"], ind["display_name"],
                 ind["category"], ind["description"], ind["output_type"],
                 json.dumps(ind["output_labels"]), json.dumps(ind["params"]),
                 f'# Built-in: see bot_template_ibkr_prod.py calc_{ind["indicator_id"].lower()}',
                 ind["usage_example"])
            )
        except Exception:
            pass
    conn.commit()
